package interaction;
import java.sql.Timestamp;
import java.util.Date;
import org.hibernate.cfg.AnnotationConfiguration;

import service.Manager;
/**
 *  Klasa wyświetla interfejs użytkownika do dodawania potrzebnych informacji faktury.
 *  
 */
public class JPAShop extends javax.swing.JFrame {

    /**
     * Creates new form JPAShop
     */
    public JPAShop() {
        manager = new Manager();
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FakturaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumerFaktury = new javax.swing.JTextField();
        NazwaNabywcy = new javax.swing.JTextField();
        AdresNabywcy = new javax.swing.JTextField();
        DodajFaktureButton = new javax.swing.JButton();
        NIPNabywcy = new javax.swing.JTextField();
        ZamowieniePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nazwa = new javax.swing.JTextField();
        ZatwierdzButton = new javax.swing.JButton();
        DodajZamowienieButton = new javax.swing.JButton();
        Cena = new javax.swing.JTextField();
        Ilosc = new javax.swing.JTextField();
        RaportPanel = new javax.swing.JPanel();
        GenerujRaportButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResultPanel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPAShop");
        setResizable(false);

        FakturaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faktura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        FakturaPanel.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel1.setText("Numer faktury:");

        jLabel3.setText("Nazwa nabywcy:");

        jLabel4.setText("NIP:");

        jLabel5.setText("Adres:");

        NumerFaktury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerFakturyActionPerformed(evt);
            }
        });

        AdresNabywcy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresNabywcyActionPerformed(evt);
            }
        });

        DodajFaktureButton.setText("Dodaj fakturę");
        DodajFaktureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajFaktureButtonActionPerformed(evt);
            }
        });

        NIPNabywcy.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout FakturaPanelLayout = new javax.swing.GroupLayout(FakturaPanel);
        FakturaPanel.setLayout(FakturaPanelLayout);
        FakturaPanelLayout.setHorizontalGroup(
            FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FakturaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FakturaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DodajFaktureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FakturaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(AdresNabywcy, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FakturaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumerFaktury, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FakturaPanelLayout.createSequentialGroup()
                        .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NazwaNabywcy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIPNabywcy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        FakturaPanelLayout.setVerticalGroup(
            FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FakturaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumerFaktury, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazwaNabywcy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIPNabywcy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FakturaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresNabywcy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(DodajFaktureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ZamowieniePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zamówienie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        ZamowieniePanel.setEnabled(false);
        ZamowieniePanel.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel7.setText("Nazwa:");

        jLabel8.setText("Cena:");

        jLabel9.setText("Ilość:");

        Nazwa.setEnabled(false);

        ZatwierdzButton.setText("Zatwierdź");
        ZatwierdzButton.setActionCommand("");
        ZatwierdzButton.setEnabled(false);
        ZatwierdzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZatwierdzButtonActionPerformed(evt);
            }
        });

        DodajZamowienieButton.setText("Dodaj zamówienie");
        DodajZamowienieButton.setEnabled(false);
        DodajZamowienieButton.setPreferredSize(new java.awt.Dimension(150, 40));
        DodajZamowienieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajZamowienieButtonActionPerformed(evt);
            }
        });

        Cena.setEnabled(false);
        Cena.setPreferredSize(new java.awt.Dimension(250, 40));

        Ilosc.setEnabled(false);
        Ilosc.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout ZamowieniePanelLayout = new javax.swing.GroupLayout(ZamowieniePanel);
        ZamowieniePanel.setLayout(ZamowieniePanelLayout);
        ZamowieniePanelLayout.setHorizontalGroup(
            ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZamowieniePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZamowieniePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(Nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ZamowieniePanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ZamowieniePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZamowieniePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DodajZamowienieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZatwierdzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ZamowieniePanelLayout.setVerticalGroup(
            ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZamowieniePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(ZamowieniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZatwierdzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajZamowienieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        RaportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raport", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        RaportPanel.setEnabled(false);

        GenerujRaportButton.setText("Generuj raport");
        GenerujRaportButton.setEnabled(false);
        GenerujRaportButton.setPreferredSize(new java.awt.Dimension(150, 40));
        GenerujRaportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerujRaportButtonActionPerformed(evt);
            }
        });

        ResultPanel.setColumns(20);
        ResultPanel.setRows(5);
        ResultPanel.setEnabled(false);
        jScrollPane2.setViewportView(ResultPanel);

        javax.swing.GroupLayout RaportPanelLayout = new javax.swing.GroupLayout(RaportPanel);
        RaportPanel.setLayout(RaportPanelLayout);
        RaportPanelLayout.setHorizontalGroup(
            RaportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RaportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RaportPanelLayout.createSequentialGroup()
                        .addGap(0, 723, Short.MAX_VALUE)
                        .addComponent(GenerujRaportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        RaportPanelLayout.setVerticalGroup(
            RaportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RaportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(GenerujRaportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FakturaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZamowieniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(RaportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FakturaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZamowieniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RaportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumerFakturyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerFakturyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerFakturyActionPerformed

    private void DodajFaktureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajFaktureButtonActionPerformed
        //Uruchamia metodę dodania faktury i przekazuje parametry  
        manager.DodajFakture(NumerFaktury.getText(), new Timestamp(new Date().getTime()), NazwaNabywcy.getText(), Integer.valueOf(NIPNabywcy.getText()), AdresNabywcy.getText()); 
        
        //Dezaktywuje panel dodania faktury celem uzupełnienia pozycji zamówienia
        FakturaPanel.setEnabled(false);
        NumerFaktury.setEnabled(false);
        NazwaNabywcy.setEnabled(false);
        NIPNabywcy.setEnabled(false);
        AdresNabywcy.setEnabled(false);
        DodajFaktureButton.setEnabled(false);       
              
        //Aktywuje panel dodania zamówienia w celu dodania informacji
        ZamowieniePanel.setEnabled(true);
        Nazwa.setEnabled(true);
        Cena.setEnabled(true);
        Ilosc.setEnabled(true);
        DodajZamowienieButton.setEnabled(true);
    }//GEN-LAST:event_DodajFaktureButtonActionPerformed

    private void AdresNabywcyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresNabywcyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresNabywcyActionPerformed

    private void DodajZamowienieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajZamowienieButtonActionPerformed
        //Dodaje nową pozycję azamówienia
        manager.DodajPozycjeZamowienia(Nazwa.getText(), Float.valueOf(Cena.getText()), Integer.parseInt(Ilosc.getText()));
        
        //Aktywuje przycisk zatwierdzenia transakcji po dodaniu szczegółów zamówienia
        ZatwierdzButton.setEnabled(true);
        
        //Czyści pola zatweirdzonego zamówienia celem podania szczegółów kolejnego zamówienia 
        Nazwa.setText("");
        Cena.setText("");
        Ilosc.setText("");
    }//GEN-LAST:event_DodajZamowienieButtonActionPerformed

    private void ZatwierdzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZatwierdzButtonActionPerformed
        manager.ZatwierdzTransakcje();
        
        //Czyści pola zatweirdzonej faktury celem podania kolejnych szczegółów
        NumerFaktury.setText("");
        NazwaNabywcy.setText("");
        NIPNabywcy.setText("");
        AdresNabywcy.setText("");
        
        //Aktywuje panel dodania faktury po zatwierdzeniu transakcji
        FakturaPanel.setEnabled(true);
        NumerFaktury.setEnabled(true);
        NazwaNabywcy.setEnabled(true);
        NIPNabywcy.setEnabled(true);
        AdresNabywcy.setEnabled(true);
        DodajFaktureButton.setEnabled(true);
        
        //Aktywuje panel dodania faktury po zatwierdzeniu transakcji
        FakturaPanel.setEnabled(true);
        NumerFaktury.setEnabled(true);
        NazwaNabywcy.setEnabled(true);
        NIPNabywcy.setEnabled(true);
        AdresNabywcy.setEnabled(true);
        DodajFaktureButton.setEnabled(true);   
        
        //Aktywuje panel generowania raportu po zatwierdzeniu transakcji
        RaportPanel.setEnabled(true);
        ResultPanel.setEnabled(true);
        GenerujRaportButton.setEnabled(true);
    }//GEN-LAST:event_ZatwierdzButtonActionPerformed

    private void GenerujRaportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerujRaportButtonActionPerformed
        ResultPanel.setText("");
        manager.pokazRaportFaktur(ResultPanel);
    }//GEN-LAST:event_GenerujRaportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPAShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPAShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPAShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPAShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //Tworzy i konfiguruje menedżera sesji Hibernate
                try{
                    Manager.factory = new AnnotationConfiguration().configure().buildSessionFactory();
                }catch (Throwable ex) {
                    System.err.println("Nieudane utworzenie objektu SessionFactory" + ex);
                    throw new ExceptionInInitializerError(ex);
                }
                
                new JPAShop().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresNabywcy;
    private javax.swing.JTextField Cena;
    private javax.swing.JButton DodajFaktureButton;
    private javax.swing.JButton DodajZamowienieButton;
    private javax.swing.JPanel FakturaPanel;
    private javax.swing.JButton GenerujRaportButton;
    private javax.swing.JTextField Ilosc;
    private javax.swing.JTextField NIPNabywcy;
    private javax.swing.JTextField Nazwa;
    private javax.swing.JTextField NazwaNabywcy;
    private javax.swing.JTextField NumerFaktury;
    private javax.swing.JPanel RaportPanel;
    private javax.swing.JTextArea ResultPanel;
    private javax.swing.JPanel ZamowieniePanel;
    private javax.swing.JButton ZatwierdzButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    //private Manager manager;
    private Manager manager;
}
